### ISSUE TITLE
How to disable recording audio and only to record video?

### ISSUE THREAD

**Issue by tzzen93** [CameraKit/camerakit-android#286] opened 2017-12-15 02:50 UTC
I don't know not to disable recording audio. I want to record only video. So, How can I do that? Thanks in advance!

**Comment by cuilongzhe** [comment] 2018-03-19 18:01
any update on this?

**Comment by austinkettner** [comment] 2018-03-19 22:24
Hey @cuilongzhe we are working on this as part of 1.x releases. I have added this to the Milestone 1.1.0 and we will keep you posted along the way.

**Comment by emersoncloud** [comment] 2018-08-08 19:32
Duplicate of #334

**Closed by emersoncloud** 2018-08-08 19:32 UTC
Labels: Priority: Low, Type: Enhancement
