### ISSUE TITLE
Preview is distorted when screen launch with portrait and then change to landscape 

### ISSUE THREAD

**Issue by tzzen93** [CameraKit/camerakit-android#294] opened 2017-12-24 03:44 UTC
The camera is distorted when screen launch with portrait and then change to landscape orientation immediately. At that timing, the camera is distorted in version com.wonderkiln:camerakit:0.13.1. Thank you very much!

**Comment by xp-vit** [comment] 2018-01-06 20:38
I think this is a duplicate of: https://github.com/wonderkiln/CameraKit-Android/issues/288

**Comment by Danm72** [comment] 2018-01-12 16:54
I'm seeing this too.

**Comment by Danm72** [comment] 2018-01-16 17:33
Was forced to lock orientations.

**Comment by austinkettner** [comment] 2018-03-08 23:25
Should be resolved in #318 can you please test that out and I will reOpen this if you comment that it is still an issue.

**Closed by austinkettner** 2018-03-08 23:25 UTC

**Comment by jatin-lakhani** [comment] 2018-05-04 08:34
+1 Its still exist with version 0.13.1
Any workaround on this?

**Comment by emersoncloud** [comment] 2018-05-04 15:32
@jatin-lakhani There is not currently a workaround in version 0.13.1. The issue should be resolved in v1.0.0 which is currently in review, #318. Try out 1.0.0 and let me know if you are running into the same issues.

**Comment by jatin-lakhani** [comment] 2018-05-07 04:17
Thank you for the reply! Version 1.0.0 is quite better but video integration seems not integrated yet. Is there any alternative I can use both feature camera capture + video recording?

**Comment by emersoncloud** [comment] 2018-05-13 15:59
@jatin-lakhani Not yet. We expect to have video support in 1.0.0 this week!

**Comment by fearenales** [comment] 2019-07-24 09:03
@emersoncloud sorry for necrobumping this issue, but is video already supported in 1.0.0? If not, any idea when it should be available and when 1.0.0 will be released?
